### ISSUE TITLE
Question about type parameters

### ISSUE THREAD

**Issue by visr** [JuliaGeometry/GeometryBasics.jl#10]
If you take for instance the definition of `LineString`:
https://github.com/SimonDanisch/GeometryBasics.jl/blob/2a36f67effe9cc623ac82f09ce76c7c66007222c/src/basic_types.jl#L169-L175

I get that `Dim` and `T` should be there, representing the number of dimensions and type of the coordinates.

But `P`, the type of `Point`, and `V`, the the type of the vector of points, seem not needed. Why are they there? Do you need them to enforce something?

Also looking at these two:
https://github.com/SimonDanisch/GeometryBasics.jl/blob/2a36f67effe9cc623ac82f09ce76c7c66007222c/src/basic_types.jl#L133-L134
You use mainly `LineP`, but can't we do without?

Sorry if it's a bit basic but I'd like to get a good handle on this.

**Comment by SimonDanisch** [comment]
If I remember correctly, you can't leave out the P in `<: LineP{Dim, T, P}` and `AbstractVector{LineP{Dim, T, P}} `.. If you do, it won't dispatch and type check correctly anymore :( 
It's annoying, but I don't think we can do without?
