### ISSUE TITLE
`Base.in(::Point, ::Circle)` assumes a circle in L-infinity norm, not L2 norm

### ISSUE THREAD

**Issue by goretkin** [JuliaGeometry/GeometryBasics.jl#108]
https://github.com/JuliaGeometry/GeometryBasics.jl/blob/2580374cf8c75d9d78f96fe6827cef2e9c1e3184/src/primitives/spheres.jl#L34-L39

is this intentional?

**Comment by sjkelly** [comment]
This might be an artifact from when we had a HyperSphere. What is the expected behavior?

**Comment by goretkin** [comment]
The set of points `p` such that `in(p, circle)` will look like a square with the current definition. It's not as wrong as it sounds: https://en.wikipedia.org/wiki/Lp_space#/media/File:Vector-p-Norms_qtl1.svg but probably is not the intention.

**Comment by sjkelly** [comment]
Yeah that is bad.

**Comment by SimonDanisch** [comment]
Oh, yeah, that's no good!

**Comment by liuyxpp** [comment]
Moreover, `y` seems not defined and `ox - x` leads to a mismatch of dimensions. Does anyone here like to make a PR? If not, I will try to submit one.
