### ISSUE TITLE
Matrix * Rectangle returns strange results

### ISSUE THREAD

**Issue by plut** [JuliaGeometry/GeometryBasics.jl#120]
julia> SA[1 1;1 -1]*GeometryBasics.Rect2D((0,0),(1,1))
    GeometryBasics.HyperRectangle{2,Int64}([0,-1], [2,2])

This should return a rotated (and scaled) rectangle. Instead it returns a bounding box for the rotated rectangle. I understand that a bounding box for the rotated rectangle might be useful, but this definitively not a matrix multiplication.

**Comment by SimonDanisch** [comment]
Well, we don't have a rotated rectangle type, so until we add that, we can't really return such a type.
