### ISSUE TITLE
Fix doctests

### ISSUE THREAD

**Issue by mforets** [JuliaGeometry/GeometryBasics.jl#126]
see stacktrace starting [here](https://github.com/JuliaGeometry/GeometryBasics.jl/runs/1749392970#step:5:9)

**Comment by visr** [comment]
Would be good to fix. See also #119.

**Comment by knuesel** [comment]
Damn I was working on this 😊 @mforets are you already working on #128? I have that mostly fixed too...

**Comment by mforets** [comment]
i was planning to do #128 after the project maintainers review https://github.com/JuliaGeometry/GeometryBasics.jl/pull/127 . but you can go ahead ! perhaps rebasing your WIP branch on `mforets/126` ?

**Comment by knuesel** [comment]
OK I'll do that.

**Comment by mforets** [comment]
(@knuesel `mforets/126` was merged so you can just rebase on `master`)
