### ISSUE TITLE
Polygon is sequence of segments, not points?

### ISSUE THREAD

**Issue by goretkin** [JuliaGeometry/GeometryBasics.jl#13]
https://github.com/JuliaGeometry/GeometryBasics.jl/blob/dfb00836d34048440e02cfb104ed197f8f5aae92/src/basic_types.jl#L232-L240
am I understanding correctly that the `Polygon` type is represented by an `AbstractVector` with `eltype` as `LineP`? I would have expected an `eltype` of `<:AbstractPoint` like in `Ngon`.

**Comment by goretkin** [comment]
Same question applies to `LineString`: https://github.com/JuliaGeometry/GeometryBasics.jl/blob/dfb00836d34048440e02cfb104ed197f8f5aae92/src/basic_types.jl#L169-L175

**Comment by asinghvi17** [comment]
This is not to be the case anymore as ov v0.5 - polygons are vectors of linestrings, and linestrings are vectors of points.
