### ISSUE TITLE
Distance computation

### ISSUE THREAD

**Issue by lassepe** [JuliaGeometry/GeometryBasics.jl#140]
I am looking for a function to compute the minimum distance between different `GeometryBasics` types, primarily

- `Point` to `Line`
- `Point` to `LineString`
- `Point` to `Polygon`

Is this functionality provided by this package or by another related package?
I could only find `GeometryBasics.min_euclideansq` which is only implemented for `GeometryBasics.HyperRectangle`.

**Comment by juliohm** [comment]
Meshes.jl has the perpendicular distance from `Point` to `Line` where a line is an actual line. I think the `Line` in GeometryBasics.jl refers to a line segment, which we call `Segment` in Meshes.jl 

We have other geometric operations implemented there, and we are trying to make them bug free and efficient. It would be nice to have your feedback if something is missing.

**Comment by lassepe** [comment]
Thank you for your  quick reply. I'll give that a try and report back if I run into any issues. Closing this for now.
