### ISSUE TITLE
Documents String typo

### ISSUE THREAD

**Issue by qiyang-ustc** [JuliaGeometry/GeometryBasics.jl#149]
See [code](https://github.com/JuliaGeometry/GeometryBasics.jl/blob/e39b2518ed1288e4fbcf701e448e22fafcd61a1c/src/lines.jl)
The function name in docs string is **intersect** but the in the definition of following function it is **intersects**.

**Comment by visr** [comment]
You're right, well spotted. Would you mind opening a pull request with the fix? The return type is also incomplete, it doesn't only return a Point, but a Bool and a Point.
