### ISSUE TITLE
Trying to plot basic geometry but decompose ordering not helping...

### ISSUE THREAD

**Issue by dsantiago** [JuliaGeometry/GeometryBasics.jl#159]
![image](https://user-images.githubusercontent.com/3484029/148667619-8501b603-5217-424e-8b65-2be5648dd09e.png)

Tried to plot a 2D rectangle, but decompose function first go all the way with the X's than the Y's and with the ordering the shapes will not work

**Comment by SimonDanisch** [comment]
They're supposed to be sorted to work well with triangle strips, and go together with `decompose(GLTriangleFace, rectangle)`

**Comment by dsantiago** [comment]
> They're supposed to be sorted to work well with triangle strips, and go together with `decompose(GLTriangleFace, rectangle)`

I see, there's a better reason to use range X than range Y. Thanks for explaining, closing it now.
