### ISSUE TITLE
Warnings after fresh compilation with julia 1.10

### ISSUE THREAD

**Issue by svretina** [JuliaGeometry/GeometryBasics.jl#203]
I just updated to 1.10 and got the following warnings. These warnings were present for
previous versions of julia.

```
┌ GeometryBasics
│  WARNING: method definition for centered at /home/svretina/.julia/packages/GeometryBasics/pjtu1/src/primitives/rectangles.jl:515 declares type variable N but does not use it.
│  WARNING: method definition for volume at /home/svretina/.julia/packages/GeometryBasics/pjtu1/src/meshes.jl:209 declares type variable FT but does not use it.
│  WARNING: method definition for volume at /home/svretina/.julia/packages/GeometryBasics/pjtu1/src/meshes.jl:209 declares type variable VT but does not use it.
│  WARNING: method definition for volume at /home/svretina/.julia/packages/GeometryBasics/pjtu1/src/meshes.jl:221 declares type variable FT but does not use it.
│  WARNING: method definition for volume at /home/svretina/.julia/packages/GeometryBasics/pjtu1/src/meshes.jl:221 declares type variable VT but does not use it.
└  
```

specs:
Julia Version 1.10.0-beta3
Commit 404750f8586 (2023-10-03 12:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  LD_LIBRARY_PATH = :/home/stamatis/.openmpi/lib/:/home/svretina/.julia/artifacts/e95ca94c82899616429924e9fdc7eccda275aa38/lib/

**Comment by nsajko** [comment]
This was fixed two years ago? Just update GeometryBasics.
