### ISSUE TITLE
Deploy docs

### ISSUE THREAD

**Issue by asinghvi17** [JuliaGeometry/GeometryBasics.jl#23]
We have docs but they aren't deployed.  @SimonDanisch if you could add a Github secret token to the repo (see https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Authentication:-SSH-Deploy-Keys-1, https://bramtayl.github.io/OnlinePackage.jl/latest/), I can make a PR for doc deployment through Github Actions?

FWIW it's pretty easy to do this through OnlinePackage.jl.  The workflow is:
```julia
using OnlinePackage
u = OnlinePackage.User("JuliaGeometry", readchomp("path/to/github/token"), "/usr/bin/ssh-keygen")
put_online(u, "GeometryBasics.jl")
```

**Comment by SimonDanisch** [comment]
Hm, I added a documenter key...Whats supposed to be in `eadchomp("path/to/github/token")`?

**Comment by SimonDanisch** [comment]
I tried putting the key from documenter in there (public/private) which didn't seem to work

**Comment by asinghvi17** [comment]
It should be a Github personal access token, forgot to specify :D

**Comment by SimonDanisch** [comment]
Thanks! Should be done

**Comment by visr** [comment]
The docs don't seem to be online? Or is the link on the readme wrong? http://juliageometry.github.io/GeometryBasics.jl

**Comment by asinghvi17** [comment]
https://juliageometry.github.io/GeometryBasics.jl/dev/
