### ISSUE TITLE
heterogeneous geometry collection

### ISSUE THREAD

**Issue by visr** [JuliaGeometry/GeometryBasics.jl#50]
Sorry for spamming the issues, but just want to get some of them out of my head :)

This issue is somewhat similar to #49, but that is about features (geometries + properties) with heterogeneous geometry types in a feature collection.

Some formats, like GeoJSON for instance, also support heterogeneous geometry collections, which are multigeometries like the multipoint or multipolygon we already have, but can consist of different geometry types. In GeoJSON it is called [GeometryCollection](https://tools.ietf.org/html/rfc7946#section-3.1.8). I'm wondering how we could represent them. It may be nice to have a geometry type like this in or based on this package, even if it will be hard to optimize.

EDIT: for now I just went with a bare Vector, though it may be nice to have that vector in a GeometryCollection type: 
https://github.com/visr/GeoJSONTables.jl/blob/4104e66a638814d77ef98af1d205450549361519/test/basics.jl#L74-L76

**Comment by asinghvi17** [comment]
I guess that this isn't really needed with GeoInterface geometry collection wrappers now?
