### ISSUE TITLE
GB.meta() errors for MultiLineString( )

### ISSUE THREAD

**Issue by Sov-trotter** [JuliaGeometry/GeometryBasics.jl#52]
```
julia> GB.meta(GB.MultiLineString([GB.LineString([Point(0.0), Point(1.0)], [1, 2])]), boundingbox = Shapefile.Rect(0.0, 0.0, 100.0, 100.0))
ERROR: Metadata needs to be an array with the same length as data items. Found: Shapefile.Rect
```
One workaround is passing the metadata as `boundingbox = [Rect(0.0, 0.0, 100.0, 100.0)]` but I wonder if it's correct. 
But this approach doesn't work for more than one items in metadata.
```
julia> GB.meta(GB.MultiLineString([GB.LineString([Point(0.0), Point(1.0)], [1, 2])]); m=[0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0, 22.0, 24.0, 26.0, 28.0], boundingbox = Rect(0.0, 0.0, 100.0, 100.0))
ERROR: Metadata array needs to have same length as data. Found 1 data items, and 15 metadata items
```
```
julia> a = GB.meta(GB.MultiLineString([GB.LineString([Point(0.0), Point(1.0)], [1, 2])]); m=[[0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0, 22.0, 24.0, 26.0, 28.0]], boundingbox = [[Rect(0.0, 0.0, 100.0, 100.0)]])
julia> meta(a)
ERROR: type NamedTuple has no field meta
```

**Comment by SimonDanisch** [comment]
You want one multilinestring having one boundingbox?
Multilinestring doesn't have a metatype yet:
https://github.com/JuliaGeometry/GeometryBasics.jl/blob/master/src/metadata.jl#L166
So, that doesn't actually work yet.

**Comment by Sov-trotter** [comment]
So how do you think I should progress with creating a polyline for Shapefile?

**Comment by Sov-trotter** [comment]
So how do you think I should progress with creating a polyline for Shapefile?

**Comment by Sov-trotter** [comment]
So how do you think I should progress with creating a polyline for Shapefile while also being able to add extra stuff into metadata?

**Comment by SimonDanisch** [comment]
Add a metatypes to GeometryBasics, similar to the MultiPoint!

**Comment by Sov-trotter** [comment]
Hey, I was writing a type for MultiPatch type and realized that Mesh didn't have a metatype. I tried something similar to MultiPoint and it did work. Should I push it to #53 ?
