### ISSUE TITLE
Docs reference `isdecomposable` which no longer exists

### ISSUE THREAD

**Issue by rdeits** [JuliaGeometry/GeometryBasics.jl#55]
The decomposition docs at https://juliageometry.github.io/GeometryBasics.jl/dev/decomposition/ still mention `isdecomposable`:

```julia
# Let's take SimpleRectangle as an example:
# Below is a minimal set of decomposable attributes to build up a triangle mesh:
isdecomposable(::Type{T}, ::Type{HR}) where {T<:Point, HR<:SimpleRectangle} = true
isdecomposable(::Type{T}, ::Type{HR}) where {T<:Face, HR<:SimpleRectangle} = true
```

but that function doesn't exist in GeometryBasics. I'm guessing this left over from the GeometryTypes API. 

Can we just implement `decompose` now instead of `decompose` and `isdecomposable`?

**Comment by SimonDanisch** [comment]
Yes, that's right!

**Comment by visr** [comment]
Can be closed :)
