### ISSUE TITLE
Primitive to Signed Distance Field

### ISSUE THREAD

**Issue by weymouth** [JuliaGeometry/GeometryBasics.jl#72]
I need the capability to compute the signed distance function to a primitive. (See  https://discourse.julialang.org/t/which-package-function-for-signed-distance-fields/43487)

Since any(?) other primitive can can meshed, the first order of business would be a mesh2SDF function. I've found similar functions coded up in other languages (see post above). I would be happy to add this capability myself, but I'm pretty new to Julia (<1 month) and unlikely to get it in the package in a way that works for everyone. 

Let me know if people are interested in this and willing to refactor some hacked together code.

**Comment by sjkelly** [comment]
I am 100% interested in this. I'm a little bandwidth constrained, but I should have enough time to refactor/optimize though if you put something together. Would love to have this for the solid modelling and path planning ecosystem.

**Comment by SimonDanisch** [comment]
This got moved out of GeometryBasics and if it will get anywhere, I don't think we'll add it here ;)

**Comment by weymouth** [comment]
True enough. Where did this move?

**Comment by sjkelly** [comment]
There are many routines in Descartes:
https://github.com/juliageometry/descartes.jl

**Comment by weymouth** [comment]
Ah great. I missed the memo on this one.
