### ISSUE TITLE
Bounding box API

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/GeometryBasics.jl#88]
First let me say that the new documentation is really helpful. I am adding GeometryBasics.jl as a dependency in GeoStats.jl soon given that things are getting in place nicely here.

I've noticed that the boundingboxes.jl file contains axis-aligned bounding box algorithms for the different primitives and geometries. May I submit a PR replacing the `Rect` constructors by an actual `boundbox` function to be exported by the package? This way we separate the algorithm of bounding box from the actual constructor of the rectangle primitive. In the future, we could have alternative algorithms to the `boundbox` like for example convex and concave hulls `convhull` and `conchull`.

**Comment by SimonDanisch** [comment]
That'd be kind of cool!
Although, I do like, that one can so easily specify the element type by using Rect...
Also, we'd need to think about the name, to not start lots of conflicts!

**Comment by juliohm** [comment]
Wouldn't it make sense to inherit the element type of the object inside the bounding box? What is the use case you have in mind where the bounding box will have a different element type? By element type you mean coordinate type, correct? Also, I think it would still be easy to use the `Rect` constructors to convert from one `Rect` to another with a different coordinate type after the bounding box is computed. I think it is beneficial overall to separate these things. I will prepare a PR accordingly and we can review from there :)

**Comment by SimonDanisch** [comment]
Yeah, it's not a big thing ;) Inheriting element type seems fine

**Comment by juliohm** [comment]
Fixed in branch `cleanup`.
